#ifndef __ERROR_H
#define __ERROR_H

typedef enum
{
	ACMEE_SUCCESS = 0,
	ACMEE_OTHER,
	ACMEE_KEY_UNSUPPORTED_TYPE,
	ACMEE_FILE_NOACCESS,
	ACMEE_ACCOUNT_NOTEXIST,
	ACMEE_ACCOUNT_NOTCREATED,
	ACMEE_ORDER_UNSUPPORTED_TYPE,
	ACMEE_CHALLENGE_NOTFOUND
} acmee;

#endif /* __ERROR_H */
